
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: MKJJO
subtitle: "A free HTML5 agency template"
url: "https://mkjjo.github.io"
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.jpg"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."


tipue_search:
  include: # 포함할 url을 선택한다.
    pages: false # posts 폴더 이외에 다른 문서 선택 여부 (true일 경우 모든 url이 포함된다.)
    collections: []
  exclude: # 제외시킬 url을 선택한다.
    files: [search.html, index.html]
    categories: []
    tags: []



# plugins:
#   - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#   - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# disqus:
#   shortname: mkjjo
#

collections:
  tags:
    output: true
    permalink: /tags/:path/
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
